const CommunityInitialValues = (communityInfo) => {
  return {
    main_data: {
      community_city_id: communityInfo?.community?.community_city_id,
      community_developer_id:
      communityInfo?.community?.community_developer_id,
      // community_agent_id:
      // communityInfo?.community?.community_agent_id,
      community_map: communityInfo?.community?.community_map,
      community_latitude: communityInfo?.community?.community_latitude,
      community_longitude: communityInfo?.community?.community_longitude,
      community_title_en: communityInfo?.community?.community_title_en,
      community_title_ar: communityInfo?.community?.community_title_ar,
      community_title_fr: communityInfo?.community?.community_title_fr,
      community_title_de: communityInfo?.community?.community_title_de,
      community_title_ru: communityInfo?.community?.community_title_ru,
      community_title_se: communityInfo?.community?.community_title_se,
      community_menu_title_en: communityInfo?.community?.community_menu_title_en,
      community_menu_title_ar: communityInfo?.community?.community_menu_title_ar,
      community_menu_title_fr: communityInfo?.community?.community_menu_title_fr,
      community_menu_title_de: communityInfo?.community?.community_menu_title_de,
      community_menu_title_ru: communityInfo?.community?.community_menu_title_ru,
      community_menu_title_se: communityInfo?.community?.community_menu_title_se,
      community_slug_en: communityInfo?.community?.community_slug_en,
      community_slug_ar: communityInfo?.community?.community_slug_ar,
      community_slug_fr: communityInfo?.community?.community_slug_fr,
      community_slug_de: communityInfo?.community?.community_slug_de,
      community_slug_ru: communityInfo?.community?.community_slug_ru,
      community_slug_se: communityInfo?.community?.community_slug_se,
      community_short_description_en: communityInfo?.community?.community_short_description_en,
      community_short_description_ar: communityInfo?.community?.community_short_description_ar,
      community_short_description_fr: communityInfo?.community?.community_short_description_fr,
      community_short_description_de: communityInfo?.community?.community_short_description_de,
      community_short_description_ru: communityInfo?.community?.community_short_description_ru,
      community_short_description_se: communityInfo?.community?.community_short_description_se,
      community_description_en: communityInfo?.community?.community_description_en,
      community_description_ar: communityInfo?.community?.community_description_ar,
      community_description_fr: communityInfo?.community?.community_description_fr,
      community_description_de: communityInfo?.community?.community_description_de,
      community_description_ru: communityInfo?.community?.community_description_ru,
      community_description_se: communityInfo?.community?.community_description_se,
      community_is_active: communityInfo?.community?.community_is_active,
      community_is_show_header_menu: communityInfo?.community?.community_is_show_header_menu,
      community_is_show_footer: communityInfo?.community?.community_is_show_footer,
      community_sorting: communityInfo?.community?.community_sorting,
      community_image_alt_en: communityInfo?.community?.community_image_alt_en,
      community_image_alt_ar: communityInfo?.community?.community_image_alt_ar,
      community_image_alt_fr: communityInfo?.community?.community_image_alt_fr,
      community_image_alt_de: communityInfo?.community?.community_image_alt_de,
      community_image_alt_ru: communityInfo?.community?.community_image_alt_ru,
      community_image_alt_se: communityInfo?.community?.community_image_alt_se,
      community_image_title_en: communityInfo?.community?.community_image_title_en,
      community_image_title_ar: communityInfo?.community?.community_image_title_ar,
      community_image_title_fr: communityInfo?.community?.community_image_title_fr,
      community_image_title_de: communityInfo?.community?.community_image_title_de,
      community_image_title_ru: communityInfo?.community?.community_image_title_ru,
      community_image_title_se: communityInfo?.community?.community_image_title_se,
    },
    seo: {
      community_seo_meta_description_en: communityInfo?.seo?.community_seo_meta_description_en,
      community_seo_meta_description_ar: communityInfo?.seo?.community_seo_meta_description_ar,
      community_seo_meta_description_fr: communityInfo?.seo?.community_seo_meta_description_fr,
      community_seo_meta_description_de: communityInfo?.seo?.community_seo_meta_description_de,
      community_seo_meta_description_ru: communityInfo?.seo?.community_seo_meta_description_ru,
      community_seo_meta_description_se: communityInfo?.seo?.community_seo_meta_description_se,
      community_seo_meta_title_en: communityInfo?.seo?.community_seo_meta_title_en,
      community_seo_meta_title_ar: communityInfo?.seo?.community_seo_meta_title_ar,
      community_seo_meta_title_fr: communityInfo?.seo?.community_seo_meta_title_fr,
      community_seo_meta_title_de: communityInfo?.seo?.community_seo_meta_title_de,
      community_seo_meta_title_ru: communityInfo?.seo?.community_seo_meta_title_ru,
      community_seo_meta_title_se: communityInfo?.seo?.community_seo_meta_title_se,
      community_seo_meta_keywords_en: communityInfo?.seo?.community_seo_meta_keywords_en,
      community_seo_meta_keywords_ar: communityInfo?.seo?.community_seo_meta_keywords_ar,
      community_seo_meta_keywords_fr: communityInfo?.seo?.community_seo_meta_keywords_fr,
      community_seo_meta_keywords_de: communityInfo?.seo?.community_seo_meta_keywords_de,
      community_seo_meta_keywords_ru: communityInfo?.seo?.community_seo_meta_keywords_ru,
      community_seo_meta_keywords_se: communityInfo?.seo?.community_seo_meta_keywords_se,
    },
  }
}

export default CommunityInitialValues;